### ISSUE TITLE
Oauth 1.0 Verification issue

### ISSUE THREAD

**Issue by twalling** [fraxedas/eloqua-oauth#1]
After a few hours of debugging, I found that I had to change the way in which I was using the verification utility. I ended up doing the following:

`verification.verify(uri, method, client_secret, '');`

because per [Eloqua docs](http://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#Developers/GettingStarted/Authentication/validating-a-call-signature.htm%3FTocPath%3DGetting%2520started%2520with%2520Oracle%2520Eloqua%2520APIs%7CAuthentication%7COAuth%2520signing%7C_____1) they expect the key to be `your app's Client Secret with an appended ampersand`

When I looked at `verification_private.js`, I noticed it was creating a signing key by concatenating the client ID and client secret. By changing how I was calling verify I was able to get the key that Eloqua expected and verification now works.

I don't know if this was a change from how Eloqua used to do things but could be something to look at either from a doc and/or code perspective.

**Comment by fraxedas** [comment]
@twalling This should be fixed in v2.0.0
Thanks for noticing.
