### ISSUE TITLE
issue on refresh token

### ISSUE THREAD

**Issue by facascante** [fraxedas/eloqua-oauth#2]
hi,

i'm using your package and it seems good but lately i notice there is a problem with the code.

it still return true when there is no error and the response.statuCode >= 400

```
oauth.request.post(options, function (error, response, body) {
            if (!error && response.statusCode < 400 && body.refresh_token && body.access_token) {
                next(null, body);
            }else{
                next(error, null);
            }
        });

```

can you change the validation
```

  if (!error && response.statusCode < 400 && body.refresh_token && body.access_token) {
                next(null, body);
}else if(response.statusCode >= 400){
                next(response, null);
            }            
}else{
                next(error, null);
            }
        });

```

statusCode: 400,
statusMessage: 'Bad Request',
 body: 
{ error: 'invalid_grant',
error_description: 'The refresh token is incorrect, malformed, expired, or has been invalidated.' } }

**Comment by fraxedas** [comment]
Hi @facascante,
Thanks for reporting the issue.
Can you please send a pull request for the fix?

thanks,
Oscar

**Comment by facascante** [comment]
done https://github.com/fraxedas/eloqua-oauth/pull/3

**Comment by facascante** [comment]
editted to pass the test too. :

**Comment by fraxedas** [comment]
Thanks for the he

**Comment by fraxedas** [comment]
Thanks for the help
